### ISSUE TITLE
Unable to drag and drop text selection into address bar or anywhere else while extension is on.

### ISSUE THREAD

**Issue by pbakes** [ixrock/XTranslate#34] opened 2021-03-27 19:25 UTC
With the extension disabled you can double-click on a word or text body and drag it into the address bar, with it enabled the popup window overrides any ability to drag text around.

**Comment by ixrock** [comment] 2021-03-29 10:54
Can't reproduce since D&D of selected text doesn't work at all.. 🤔 (with enabled nor disabled extension).
Checked in Chrome 89 (latest), mac OS Big Sur 11.2.1.

**Comment by ixrock** [comment] 2021-06-11 12:02
Closing for non-activity of the issue.

**Closed as completed by ixrock** 2021-06-11 12:02 UTC
